### ISSUE TITLE
Стиль кода

### ISSUE THREAD

**Issue by whitebyte** [DarkRiDDeR/inDCMS#1]
Привет!
Используется ли в проекте какой-то конктретный стиль оформления кода?
http://dlang.org/dstyle.html ? Что-то свое? Какой-нибудь K&R?

**Comment by DarkRiDDeR** [comment]
Привет. Как основа — стиль Олмана. Но бывает, что иногда мешается с K&R (try/catch почему-то люблю в стиле K&R оформлять). Главное — читабельность. Также не слудует переполнять строку, лучше сделать переносы.
В шаблонах temple K&R, т.к. данный стиль более компактен.
