### ISSUE TITLE
Обсуждение списка планируемых функций и изменений

### ISSUE THREAD

**Issue by denizzzka** [DarkRiDDeR/inDCMS#10]
> регистрация пользователей

Мне кажется, это можно легко сделать это аддоном

> авторизация/выход

/// ditto

> защита от брута паролей (+капча) 

/// ditto

Какпчу можно сделать отдельным аддоном, имеющим в зависимостях аддон регистрации/авторизации

> восстановление паролей

тоже можно сделать отдельным аддоном

> регистрация/смена пароля с помощью кода активации, высланного на e-mail

аддон рассылки почты (пригодится ещё для чего-нибудь) + аддон кода активации

> профиль пользователя, его редактирование

аддон!

> новостная лента

аддон!

> комментарии к новостям

аддон

> создание статичных страниц в админ-панели
> раздел админ-панели для выделения различных прав доступа для пользователей (админ, модератор, модератор комментариев и т.д.)

аддон прав доступа, который в зависимостях у аддона регистрации пользователей

> опросы

аддон

> форум

аддон (может даже несколько)

В связи с вышеизложенным - идея: интерфейс аддонов позволит вообще всё собирать из модулей. Начать писать их можно в любом порядке. Такой вот unix-way получится.

**Comment by DarkRiDDeR** [comment]
Так и будем )) Главно продумать нормальное внедрение этих самых аддонов

**Comment by denizzzka** [comment]
Внедрение выглядит просто: пусть аддон наследует примерно такой класс:

```d
interface AddonBase
{
    void install(); /// Вызывается при установке аддона (обсуждали в https://github.com/DarkRiDDeR/inDCMS/issues/8)
    void purge(); /// Вызывается при полном удалении аддона
    /// (тут прочие методы из той серии)

    someHTMLtype getHTMLcontent(); /// Пришёл шаблонизатор и просит чтобы модуль отдал свой кусочек содержимого на страничку
    void pageBeginRender() {}; /// на вебсервер пришёл запрос на страницу - эта функция будет вызвана автоматически для использования для внутренних нужд модуля.
}
```

и, собственно, это всё!

**Comment by denizzzka** [comment]
А для зависимостей и версионирования аддонов можно использовать dub. И на первых порах даже официальный репозиторий для хранения этих аддонов, а потом (когда их станет больше ~10) запилить свой.

**Comment by DarkRiDDeR** [comment]
Да мне кажется пусть пока все аддоны в движке обитают

**Comment by denizzzka** [comment]
> Да мне кажется пусть пока все аддоны в движке обитают

угу
