### ISSUE TITLE
PostgreSQL. Выделение прав под addons

### ISSUE THREAD

**Issue by DarkRiDDeR** [DarkRiDDeR/inDCMS#11]
Нужна оценка того, кто разбирается в данном виде БД. Накидал схему БД, смотрим в папке devolopment. Файлы инсталляции для БД соответственно в папке install (названия папок соответствуют названиям аддонов).
1) Есть системное дополнение (системный модуль system). Создаётся БД indcms от имени суперпользователя.
2) Создаётся роль - indcms_system с полными правами в БД indcms
3) От имени суперпользователя также создаються таблицы addons и addons_permissions и в них заносятся базовые записи (внизу файла)
4) Дальше создаются таблицы users, users_permissions, users_new. Для них создаётся роль indcms_users (для аддона users), имеющая права на запись, чтение, обновление в таблицах users, users_permissions, users_new, addons_permissions. Также роль indcms_user может только читать данные из таблицы addons.

Этим самым получается добиться разграничения прав доступа для аддонов. Прошу оценить файлы  "/install/название дополнения/install.sql". Мне главное волнует вопрос: правильно ли я выделил права доступа, т.к. с данным видом бд работаю впервые.

**Comment by denizzzka** [comment]
Выложите .sql - он лучше всего читается

**Comment by DarkRiDDeR** [comment]
inDCMS/install/system/install.sql
 inDCMS/install/users/install.sql

**Comment by DarkRiDDeR** [comment]
У меня ещё такой вопрос. Есть ли в PostgreSQL аналог возрата кол-ва секунд с эпохи UNIX, как, например, unix_timestamp() в MySQL. Формат больно удобный.

**Comment by denizzzka** [comment]
Поехали! :)

* Если согласен с тем, что будет purge() (https://github.com/DarkRiDDeR/inDCMS/issues/10#issuecomment-127328836) то сразу вместе с функциями создающими что-либо пиши функции, которые это что-то грохают.

* Не надо в CREATE DATABASE ничего, кроме названия указывать - тогда оно скопирует с базы-шаблона всё это (локали и т.п.). Мы же не хотим, чтобы только русскоязычные могли пользоваться этой CMS?

**Comment by denizzzka** [comment]
> У меня ещё такой вопрос. Есть ли в PostgreSQL аналог возрата кол-ва секунд с эпохи UNIX, как, например, unix_timestamp() в MySQL. Формат больно удобный.

Есть но он не очень удобный. (Ага!)
Вообще, на тему времени в SQL всё очень круто, так что это можно сделать темой отдельного тикета.

**Comment by denizzzka** [comment]
Вместо такого камента лучше сразу задать CONSTRAINT CHECK, чтобы отличные от латиницы буквы нельзя было вбить

```sql
COMMENT ON COLUMN "addons_permissions"."systemName" IS 'only english';
```

А чем вызвано такое ограничение вообще?

**Comment by denizzzka** [comment]
```sql
ALTER TABLE "addons_permissions" ADD CONSTRAINT "Relationship4" FOREIGN KEY ("idAddon")
	REFERENCES "addons" ("idAddon") ON DELETE NO ACTION ON UPDATE NO ACTION;
```
тут вместо NO ACTION можно сразу добавить возможность автоматического удаления и переименования строки и ключа (сделаю как собираться начнёт)

**Comment by DarkRiDDeR** [comment]
> Если согласен с тем, что будет purge() (#10 (comment)) то сразу вместе с функциями создающими что-либо пиши функции, которые это что-то грохают.

Как-то так

> Не надо в CREATE DATABASE ничего, кроме названия указывать - тогда оно скопирует с базы-шаблона всё это (локали и т.п.). Мы же не хотим, чтобы только русскоязычные могли пользоваться этой CMS?

Понял

> >    У меня ещё такой вопрос. Есть ли в PostgreSQL аналог возрата кол-ва секунд с эпохи UNIX, как, например, unix_timestamp() в MySQL. Формат больно удобный.

> Есть но он не очень удобный. (Ага!)
Вообще, на тему времени в SQL всё очень круто, так что это можно сделать темой отдельного тикета если встанет вопрос о времени более предметно.

https://github.com/DarkRiDDeR/inDCMS/issues/12


Спасибо за выявление недочётов

**Comment by denizzzka** [comment]
Неправильно что в system создаются юзеры, если таблица юзеров уже появляется после них из другого аддона.

Пусть принадлежность аддонам юзеров определяется из аддона users. Без этого модуля у аддонов просто не будет никакого понятия о правах.

**Comment by DarkRiDDeR** [comment]
-- permissions for addons
INSERT INTO "addons_permissions" ("idAddon", "systemName")
  VALUES  (1, 'admin'), /* администратор сайта */
          (1, 'user');  /* обычный пользователь (по умолчанию) */ 

Это права доступа для аддонов. System это глобальный, системный аддон. Т.е. есть например Вася Пупкин с правом доступа admin. Он администратор сайта

**Comment by denizzzka** [comment]
> Это права доступа для аддонов. System это глобальный, системный аддон. Т.е. есть например Вася Пупкин с правом доступа admin. Он администратор сайта

Да, но если аддон users не стоит, то никакого админа у сайта просто нет. Нельзя зайти и отредактировать, потому что редактор требует users. Или не редактор, а ещё отдельный модуль, который следит только за правами на всё.

**Comment by DarkRiDDeR** [comment]
Есть модуль system, который распростроняет свой действие на всё. Пусть даже пользователей не будет, дополнения users не будет. Право доступа admin и user будут, но ими никто воспользоваться не сможет, т.к. вся основаная работа с выдачей прав будет всё равно происходить в дополнении users

**Comment by denizzzka** [comment]
> Есть модуль system, который распростроняет свой действие на всё. Пусть даже пользователей не будет, дополнения users не будет.

Угу.

> Право доступа admin и user будут,

Ну нарушение же инкапсуляции! И смысла в них нет, ведь воспользоваться нельзя.

> но ими никто воспользоваться не сможет, т.к. вся основаная работа с выдачей прав будет всё равно происходить в дополнении users

Именно. Когда поставят users там будет вписано, что на системные таблицы такие-то юзеры (admin, например) имеет право. И всё получится красиво!

**Comment by DarkRiDDeR** [comment]
>  Вместо такого камента лучше сразу задать CONSTRAINT CHECK, чтобы отличные от латиницы буквы нельзя было вбить
А чем вызвано такое ограничение вообще?

К сессии пользователя будут прилепляться права доступа. И при перемещении по страница дополнения их будут проверять. С англ. здесь проблем меньше намного будет. Это имена для дополнений, а не для пользователей. Т.е. если у тебя есть право, например, на модерирование сообщений гостевой, то тебе доступны такие-то функции. Ну, и т.д.

**Comment by denizzzka** [comment]
О, ещё момент!

```indcms_system```

Одобряю использование таких имён с префиксом. В постгресе есть такой момент: один движок может одновременно поддерживать несколько БД, но имена ролей для всех этих БД - общие.

На виртуальном хостинге это может иметь значение!
Для этого нужно дополнительно сделать возможность настройки этого суффикса в конфиге cms.

**Comment by denizzzka** [comment]
> К сессии пользователя будут прилепляться права доступа. И при перемещении по страница дополнения их будут проверять.

> Т.е. если у тебя есть право, например, на модерирование сообщений гостевой, то тебе доступны такие-то функции. Ну, и т.д.

Этот функционал просится в отдельный от users модуль :)

**Comment by DarkRiDDeR** [comment]
> >но ими никто воспользоваться не сможет, т.к. вся основаная работа с выдачей прав будет всё равно происходить в дополнении users

> Именно. Когда поставят users там будет вписано, что на системные таблицы такие-то юзеры (admin, например) имеет право. И всё получится красиво!

Накарявил. "Откарявлю" ))

**Comment by DarkRiDDeR** [comment]
> Одобряю использование таких имён с префиксом. В постгресе есть такой момент: один движок может одновременно поддерживать несколько БД, но имена ролей для всех этих БД - общие.
На виртуальном хостинге это может иметь значение!
Для этого нужно дополнительно сделать возможность настройки этого суффикса в конфиге cms.

Ок. Непроблема

**Comment by DarkRiDDeR** [comment]
>> К сессии пользователя будут прилепляться права доступа. И при перемещении по страница дополнения их будут проверять.
Т.е. если у тебя есть право, например, на модерирование сообщений гостевой, то тебе доступны такие-то функции. Ну, и т.д.

> Этот функционал просится в отдельный от users модуль :)

Мне кажется это лишним. Зачем сильно много плодить модулей? Данный функции хорошо уместять и в users. Создать там какой-нибудь статический класс

**Comment by denizzzka** [comment]
> Зачем сильно много плодить модулей?

Чтобы сделать проще код. Код выделения прав это же не то же самое что код проверки капчи и защиты от брутфорсов, хотя и лежат они где-то рядом.

> Данный функции хорошо уместять и в users.

Да, может. Время покажет.

**Comment by denizzzka** [comment]
К вопросу о правах - можно вот на эту штуку посмотреть:

https://github.com/rejectedsoftware/userman
This package doubles as a library that provides an embeddable user management interface for websites and as a standalone server that provides a user administration front end, as well as a RESTful service that can be used for authentication or to manage user accounts.
