### ISSUE TITLE
О времени в PostgreSQL

### ISSUE THREAD

**Issue by DarkRiDDeR** [DarkRiDDeR/inDCMS#12]
Есть ли в PostgreSQL аналог возрата кол-ва секунд с эпохи UNIX, как, например, unix_timestamp() в MySQL? Формат больно удобный.

**Comment by DarkRiDDeR** [comment]
Данный формат удобен, если постоянно подсчитывать промежутки времени. Пример: брут. Так как требуется постоянно отнимать время предыдущей попытки входа от попытки в текущее время.

**Comment by denizzzka** [comment]
> Есть ли в PostgreSQL аналог возрата кол-ва секунд с эпохи UNIX, как, например, unix_timestamp() в MySQL? Формат больно удобный.

Тут должно быть:
http://www.postgresql.org/docs/current/static/functions-datetime.html

Но в плане времени SQL мощнее unix time и того, что есть в библиотеках D.

**Comment by DarkRiDDeR** [comment]
Спс, посмотрю. Таблицы некоторые подправлю под более "красивое" время

**Comment by denizzzka** [comment]
Советую не спешить. Лучше добавлять поля только тогда, когда они реально понадобятся, не "на будущее".

Т.е., встанет задача защиты от брутфорса - подумаем как красиво воткнуть. (Кому как, но мне сейчас не очевидно надо ли считать брутфорс прямо на сервере - тогда он может просто true/false вернуть на тему брутят его сейчас или как, или нет/)
