### ISSUE TITLE
PostgreSQL. ОШИБКА:  нет доступа к последовательности users_idUser_seq

### ISSUE THREAD

**Issue by DarkRiDDeR** [DarkRiDDeR/inDCMS#13]
Значит есть таблицы и роли (см. файлы):
inDCMS/install/system/install.sql
inDCMS/install/users/install.sql

Из под indcms_users пытаюсь записать данные (к примеру):
INSERT INTO "users" ("login", "password", "mail", "regTime") VALUES('uu
u', '1', 'm', CURRENT_TIMESTAMP);

Но вылазит ошибка "ОШИБКА:  нет доступа к последовательности users_idUser_seq". Не понимаю в чём дело, но знаю одно, что это из-за прав доступа, т.к. из под суперпользователя всё работает. 
Права indcms_users:
GRANT SELECT, UPDATE, INSERT, DELETE, TRUNCATE ON TABLE "users", "users_new", "users_permissions", "addons_permissions"  TO indcms_users;

**Comment by denizzzka** [comment]
Есть такая штука - sequence (последовательность). Это (пользуясь терминологией D) not pure функция, которая возвращает значения для колонок, где указан тип SERIAL.

Вот к ней доступа и нет. На неё надо дать права, но вроде, по умолчанию они и так даются норм.

Под каким пользователем создаётся, под каким пытается использовать?

**Comment by DarkRiDDeR** [comment]
Таблицы создаёт пользователь indcms_system полными правами к базе данных

**Comment by denizzzka** [comment]
Ага. Можно сделать владельцем (OWNER) этой SEQUENCE юзера, который хочет её юзать.

А лучше - группу юзеров.

**Comment by DarkRiDDeR** [comment]
"лучше - группу юзеров" будет лучше, конечное, намного

**Comment by denizzzka** [comment]
На будущее: лучше написать свою функцию, которая будет создавать уникальные 64-битные ID на базе текущего времени, уникального ключа и рандомного числа. В таком случае шардинг легче будет делать потом.

**Comment by DarkRiDDeR** [comment]
Вроде накопал
GRANT USAGE, SELECT ON SEQUENCE users_idUser_seq TO indcms_users;
Но опять ошибка:  отношение "users_iduser_seq" не существует

**Comment by DarkRiDDeR** [comment]
> На будущее: лучше написать свою функцию, которая будет создавать уникальные 64-битные ID на базе текущего времени, уникального ключа и рандомного числа. В таком случае шардинг легче будет делать потом.

На не сильно отдалённое будущее, будем надеяться

**Comment by denizzzka** [comment]
Присмотрись к ошибке. Точнее, к буквам. 

В SQL всё что не в кавычках считается lowercased

**Comment by DarkRiDDeR** [comment]
Это не из-за ковычек. Надо было сначал дать права indcms_system, а то я из под него пытался это провернуть
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO indcms_system;
а

**Comment by DarkRiDDeR** [comment]
Хотя из-за ковычек тоже :))
