### ISSUE TITLE
PostgreSQL и роли

### ISSUE THREAD

**Issue by denizzzka** [DarkRiDDeR/inDCMS#17]
Их ведь может быть не 2 (system и user), а бОльшее количество.

Предложение:

Всегда подключаться системным юзером CMS (indcms_system, например), а потом сразу после начала транзакции от имени пользовательской роли делать
```sql
SET LOCAL ROLE имя_пользователя; -- установить в текущей транзакции имя пользователя
```

Получится снижение привилегий.

**Comment by DarkRiDDeR** [comment]
> Их ведь может быть не 2 (system и user), а бОльшее количество

Если дополнение посчитает нужным, то создаст новую роль. Каждое дополнение может пользоваться ролью system (для установки хоть как необходима).

> после начала транзакции от имени пользовательской роли делать 
SET LOCAL ROLE имя_пользователя; -- установить в текущей транзакции имя пользователя

пусть дополнения сами разбираются. Это хороший вариант

**Comment by denizzzka** [comment]
> пусть дополнения сами разбираются.

Напортачат же!

Ок, придумаем потом как им песочницы поогораживать.
