### ISSUE TITLE
Кодировка исходника - UTF-16LE?!

### ISSUE THREAD

**Issue by denizzzka** [DarkRiDDeR/inDCMS#20]
Компилятор и редактор не глючат, а вот статический анализатор - вполне.

Предлагаю перекатиться на UTF-8.

**Comment by denizzzka** [comment]
https://github.com/Hackerpilot/Dscanner/issues/278

**Comment by DarkRiDDeR** [comment]
Да я в xamarin сижу, а там utf-16 по умолчанию. Да, лучше тогда на utf-8 перекатится

**Comment by denizzzka** [comment]
Жду тогда
