### ISSUE TITLE
Мелочи по именам функций и переменных

### ISSUE THREAD

**Issue by whitebyte** [DarkRiDDeR/inDCMS#3]
userRight должно быть userPermissions (и везде, где "right" в значении "права доступа" должно быть permission

controllerUsers должен называться usersController
ModelUser должно быть UsersModel (или UserModel)
dirViews должно быть viewsDir

Имена модулей рекомендуется делать lowercase, это позволяет избежать конфликтов имен (например, с точки зрения Windows, "inDCMS" и "indcms" - одно и то же, с точки зрения unix-like  нет.

Best practices из официальной вики рекомендует включения модулей от общего к частному. Я считаю, это имеет смысл. Подробнее здесь - http://wiki.dlang.org/Order_of_import_statements

**Comment by DarkRiDDeR** [comment]
Спасибо. Приму во внимание
