### ISSUE TITLE
Базу данных MySQL сразу в печку

### ISSUE THREAD

**Issue by denizzzka** [DarkRiDDeR/inDCMS#4]
Это уже даже не холивор, это медицинский факт.

**Comment by whitebyte** [comment]
И аргументация, разумеется, не заставит себя ждать? MySQL - это стандарт в большинстве CMS, которые сейчас есть на рынке. Postgres для CMS это overkill. NoSQL для CMS не имеет смысла. Ваша версия?

**Comment by denizzzka** [comment]
MySQL давно загнивает, да и изначально был крив. Он сделал своё дело в 90-е, спасибо ему, но теперь его можно закапывать.

> Postgres для CMS это overkill. 

Почему?

> NoSQL для CMS не имеет смысла. 

Это попытка сравнить тёплое с мягким. В 2015 году для сайта я бы выбрал какую-нибудь монгу-коуч-чтотамещё

**Comment by whitebyte** [comment]
> MySQL давно загнивает, да и изначально был крив.

Я хотел бы услышать конкретные технические аргументы "против". MariaDB, которая сейчас везде, вроде как живее всех живых. 

> В 2015 году для сайта я бы выбрал какую-нибудь монгу-коуч-чтотамещё

Встречный вопрос - почему? CMS предполагает работу с достаточно однородной информацией, какие плюсы у той же Mongo в данном случае? Мое скромное понимание NoSQL говорит мне, что основные его плюшки проявляются при работе с разнордными данными.

Почем у Postgres это overkill? Ну не то чтобы overkill, но я опять же не вижу плюсов, которые он может дать для CMS. Зато вижу некоторый минус в том, что по сравнению с MySQL с ним работает не так много людей. Я предполагаю, что если проект будет развиваться, то приличная часть аудитории будет состоять из людей, который решили вместо родного PHP попробовать таинственный Dlang, и не стоит отпугивать их еще одной новой технологией. Я не знаю ни одной более-менее популярной CMS не на MySQL и не вижу серьезных технических оснований ломать это положение вещей. Я не прав?

**Comment by denizzzka** [comment]
> Я хотел бы услышать конкретные технические аргументы "против". MariaDB, которая сейчас везде, вроде как живее всех живых.

http://habrahabr.ru/company/mailru/blog/248845/

>> В 2015 году для сайта я бы выбрал какую-нибудь монгу-коуч-чтотамещё
> Встречный вопрос - почему?

Потому что для сайта с текстами не так важны непротиворечивость и транзакционность бэкенда, как способность держать нагрузку. А SQL базы именно из-за наличия в них ACID и реляций всегда имеют единую точку отказа и плохо масштабируются.

**Comment by whitebyte** [comment]
Я читал эту статью. Совершенно справедливо указывается на основной плюс PG для нагруженных проектов. Но сайты на CMS (любой CMS) - это не нагруженные проекты. Простота обслуживания, удобство имеют большее значение _в данном случае_, поскольку запас по производительности, как правило, высок. Выбор PG из этих соображений - преждевременная оптимизация, которая скорее всего никогда не потребуется. А для проектов с серьезной нагрузкой ЦМС не стоит использовать в принципе, и это развязывет руки в выборе БД.

"Миллионы леммингов" - это не аргумент, так можно обфыркать любой популярный продукт с большим количеством внедрений.

**Comment by denizzzka** [comment]
> Но сайты на CMS (любой CMS) - это не нагруженные проекты. 

oh you

Да нету там никаких принципиальных различий в производительности. Как и принципиальных различий в настройке/администрировании.

> это не аргумент, так можно обфыркать любой популярный продукт с большим количеством внедрений

Проблема в том, что этот "продукт" уже помирает. То, что на нём до сих пор делают сайты миллионы людей объясняется низкой квалификацией большинства веб-программистов. Они просто не задумывались, что есть выбор.

Уточняю: я выступаю не за PostgreSQL, а против MySQL.

Проект ваш - делайте как считаете нужным.

**Comment by whitebyte** [comment]
> oh you

Протухшие мемы как аргумент в технической дискусии? 

Без обид, но я вижу евангелиста, а не обоснованную критику.

Окончательное решение за @DarkRiDDeR. В перспективе хотелось бы видеть ORM, что сгладит вопрос с выбором БД.

**Comment by denizzzka** [comment]
> Без обид, но я вижу евангелиста, а не обоснованную критику.

А я вижу человека, который осилил <s>Delphi</s> MySQL и теперь готов писать на нём всё и всегда.

> В перспективе хотелось бы видеть ORM

В 2015-то году?
https://en.wikipedia.org/wiki/Object-relational_impedance_mismatch

@DarkRiDDeR, сделайте правильный выбор!

**Comment by whitebyte** [comment]
Одни просроченные мемчики вместо общения. Даже спорить не буду, оставайтесь при своем.

**Comment by DarkRiDDeR** [comment]
О ё ё, denizzzka, вы слишком писсиместичны по отношению к MySQL. MySQL, конечно, по сравнению с той же PostgreSQL имеет минусы, но они не настолько критичны, чтобы харонить MySQL. К тому же MySQL самая популярная в мире веб-приложений, и ваше выражение "Миллионы леммингов" — не аргумент, как было замечено ранее.
Аргументы в пользу MySQL в нашем проекте:
1) Проект небольшой и нам подойдёт практически любая БД 
2) MySQL — самая популярная в вебе
3) Т.к. с MySQL знакомо большинство, то проект, использующий данную БД, будет ближе большинству людей
4) Мы имеем хорошую библиотеку для работы с MySQL: https://github.com/britseye К тому же она имеет большую и подробную документацию: http://britseyeview.com/software/mysqln/

**Comment by DarkRiDDeR** [comment]
Теперь о ORM. Данный подход имеет весомые минусы и весомые плюсы. Но не просто же так гиганты, как, например, microsoft, поддерживает ORM-проекты?

**Comment by denizzzka** [comment]
> 1) Проект не сильно большой, и нам подойдёт практически любая БД 

Да. Поэтому, рекомендую вообще отказаться от SQL.

> 2) MySQL — самая популярная в вебе

И PHP

> 3) Т.к. с MySQL знакомо большинство, то проект, использующий данную БД, будет ближе большинству людей

Они думают, что хорошо знакомы. А по факту, если им заменить её на sqlite3 то 90% из них ничего не заметят.

> 4) Мы имеем хорошую библиотеку для работы с MySQL: https://github.com/britseye К тому же она имеет большую и подробную документацию: http://britseyeview.com/software/mysqln/

Этого добра как грязи уже для каждой БД.
Я даже сам одну написал: https://github.com/denizzzka/dpq2

> Теперь о ORM. Данный подход имеет весомые минусы и весомые плюсы. Но не просто же так гиганты, как, например, microsoft, поддерживает ORM-проекты?

Ссылка на вики дадена - вопросы по ней есть?

Всё барахло, что кануло в Лету, кто-то когда-то поддерживал.

ORM — это плохая концепция и дырявая абстракция, которая создаёт проблем больше, чем решает: в ORM нет реляционной алгебры, попытки использовать ORM с RDBMS приводят к тому, что схема БД расползается в строну прикладного кода.

**Comment by DarkRiDDeR** [comment]
ORM мне самому не нравится, вопроса о внедрении данной технологии и не стояло, я лично этого не пранировал

**Comment by DarkRiDDeR** [comment]
> Да. Поэтому, рекомендую вообще отказаться от SQL.
Ну это уже изуверство какое-то )) И возвращение в средневековие
> Они думают, что хорошо знакомы. А по факту, если им заменить её на sqlite3 то 90% из них ничего не заметят.
Ну, это цифра требует досконального изучения. Я верю, что веб-мастера более мастеровитые.
> Этого добра как грязи уже для каждой БД. Я даже сам одну написал: https://github.com/denizzzka/dpq2
Посмотрю

**Comment by whitebyte** [comment]
ORM - это удобно. Как и любая абстракция, ORM имеет свою цену, но выгода от использования во многих случаях выше. Если бы все было так плохо, как объяснить популярность Doctrine, Eloquent, Propel? Hibernate? Или это тоже "барахло, что кануло в Лету", которое надо "закопать" (как ЛОРом-то повеяло).

Тот факт, что концепция ORM не всегда вписывается в ООП не будет смущать, если вспомнить о том, что ООП - не священная корова и ради академического соблюдения ООП не стоит приносить в жертву практичность. В конце концов, D - это практичный язык, если бы нам была важна академическая строгость, мы бы писали на Haskell.

**Comment by denizzzka** [comment]
> ORM - это удобно. Как и любая абстракция, ORM имеет свою цену

Цена использования ORM - отказ от RDBMS.

**Comment by denizzzka** [comment]
> > Да. Поэтому, рекомендую вообще отказаться от SQL.

> Ну это уже изуверство какое-то )) И возвращение в средневековие

Отвечал уже тут:
https://github.com/DarkRiDDeR/inDCMS/issues/4#issuecomment-126622562

CMS это не банк. В CMS важна скорость, а не непротиворечивость и консистентность данных в каждый момент времени.

Любая успешная CMS упрётся в централизованную "натуру" SQL-сервера. (Когда в Сбере в Москве лежит Оракловый SQL-сервер процессинг карт останавливается по всей РФ.)

**Comment by DarkRiDDeR** [comment]
PostgreSQL меня больше прельщает. denizzzka, твоя либа dpq2 нормально работает? Планируется ли дальше её поддерживать, развивать?

**Comment by denizzzka** [comment]
> PostgreSQL меня больше прельщает. denizzzka, твоя либа dpq2 нормально работает?

Да. И она покрыта юнит- и интеграционными тестами.

> Планируется ли дальше её поддерживать, развивать?

Вообще, там особо и развивать нечего - оно просто работает да и всё, собственно. Биндинг к БД при наличии библиотеки это относительно просто.

Есть ещё https://github.com/pszturmaj/ddb - у неё больше звёздочек (может просто документация лучше?)

А ещё есть наша https://github.com/DSoftOut/pgator - она вообще другая, предоставляет JSON RPC API. Мы используем её в продакшене, но она не гонялась толком под реальной нагрузкой, какая бывает у популярных сайтов.

И, последний раз скажу: считаю что SQL тут вообще не надо использовать.

**Comment by DarkRiDDeR** [comment]
> ORM - это удобно. Как и любая абстракция, ORM имеет свою цену, но выгода от использования во многих случаях выше. Если бы все было так плохо, как объяснить популярность Doctrine, Eloquent, Propel? Hibernate? Или это тоже "барахло, что кануло в Лету", которое надо "закопать" (как ЛОРом-то повеяло).

Это конечно верно. Но мне лично по душе "чистые" запросы

**Comment by whitebyte** [comment]
> Любая успешная CMS упрётся в централизованную "натуру" SQL-сервера.

Наиболее успешные ЦМС у нас - Wordpress, Joomla, MODX, Drupal, в России еще Битрикс. Все как одна - на MySQL (MODX еще может на MSSQL благодаря ORM). У каждой - свои плюсы и свои проблемы, но производительность SQL в их число, как правило, не входит. Исключение - Битрикс, но это отдельная грустная история, и смена БД его вряд ли бы ускорила.

**Comment by whitebyte** [comment]
Впрочем, я соглашусь с тем, что в любом случае ORM - не дело первой необходимости.

**Comment by DarkRiDDeR** [comment]
> Наиболее успешные ЦМС у нас - Wordpress, Joomla, MODX, Drupal, в России еще Битрикс. Все как одна - на MySQL (MODX еще может на MSSQL благодаря ORM). У каждой - свои плюсы и свои проблемы, но производительность SQL в их число, как правило, не входит. Исключение - Битрикс, но это отдельная грустная история, и смена БД его вряд ли бы ускорила.

Это, конечное, да. Но PostgreSQL определённо лучше MySQL.

**Comment by whitebyte** [comment]
Я сдаюсь. Делайте, как считаете нужным.

**Comment by DarkRiDDeR** [comment]
А меня кажется переубедили )) И мой взор пал на PostgreSQL

**Comment by denizzzka** [comment]
> Наиболее успешные ЦМС у нас - Wordpress, Joomla, MODX, Drupal, в России еще Битрикс. Все как одна - на MySQL

Они неправильно используют SQL. Для их задач как раз монга бы подошла (но её не было во времена, когда они проектировались)

**Comment by DarkRiDDeR** [comment]
> Впрочем, я соглашусь с тем, что в любом случае ORM - не дело первой необходимости.

Я планирую запилить совсем простой ORM, который RDBMS практически никак не затронет. Что-то вроде типа db.query("SELECT * FROM table WHERE name = ? ABD family = ?", array params), чтобы ескейпингом не заниматься лишним

**Comment by denizzzka** [comment]
Это уже в самой библиотеке есть обычно (в dpq2 это Connection.exec(QueryParams))

**Comment by DarkRiDDeR** [comment]
> Это уже в самой библиотеке есть обычно (в dpq2 это Connection.exec(QueryParams))

Ясно, спс
