### ISSUE TITLE
Дизайн.

### ISSUE THREAD

**Issue by DarkRiDDeR** [DarkRiDDeR/inDCMS#6]
Как вам такая идея?

https://yadi.sk/d/04mVQQ--iCiVW

**Comment by denizzzka** [comment]
Как по мне: кубики прикольно крутятся. Заработает ли это в телефоне? Будет ли видно сайт там достаточно хорошо?

Вообще, доступность важна: слепые и слабовидящие люди тоже хотят ходить по сайтам.

Дополнительно, предлагаю ход конём: целиком передрать дизайн сайта и всю стилистику у http://vibed.org/

**Comment by DarkRiDDeR** [comment]
> Как по мне: кубики прикольно крутятся. Заработает ли это в телефоне? Будет ли видно сайт там достаточно хорошо?

Пока делал диз для компов, т.к. это основаная аудитория, но владельцев телефонов не планирую обделять. Где анимация не работает, будут просто картинки. В сенсорных мониторах анимация пока не будет работать, но андроид её норамально поддерживает. Планирую сделать так:  по первому клику запускается анимация, по второму клику переход в раздел

> Вообще, доступность важна: слепые и слабовидящие люди тоже хотят ходить по сайтам.

Да

> Дополнительно, предлагаю ход конём: целиком передрать дизайн сайта и всю стилистику у http://vibed.org/

Мне кажется это слишком. Лучше накидать свою, конечное, можно что-то взять, но я не старонник так называемого "передира"

**Comment by denizzzka** [comment]
Наоборот, будет круто - CMS как логическое продолжение vibe.d

**Comment by DarkRiDDeR** [comment]
> Наоборот, будет круто - CMS как логическое продолжение vibe.d

Ну дизайнов вообще можно сделать несколько

**Comment by denizzzka** [comment]
угу

**Comment by whitebyte** [comment]
К сожалению, дизайн слаб. Поскольку @DarkRiDDeR не вебдизайнер по професси (как я понимаю), винить его нельзя. Для недизайнера сделать приличный внешний вид можно одним способом - взять набор готовых элементов, какой нибудь Bootsptrap, Foundation и т.д. Будете рисовать с нуля - успеха не будет. 

Идея позаимствовать дизайн с vibed.org мне тоже кажется странной. OctoberCMS построена на базе Laravel, но дизайн сайта уникален. Drupal 8 построен на базе Symfony, но дизайн тоже свой.

"Кубики" и прочее 3D уместны на сайте вебстудии, какой-нибудь промостранице, но на сайте утилитарного назначения они всех утомят через 2 дня.

**Comment by DarkRiDDeR** [comment]
Не, я не дизайн показывал, я предложил идею кубиков

**Comment by whitebyte** [comment]
Логотип в SVG - http://rghost.ru/6fN2PV5ZZ
В отличие от PNG, выглядит четко при любом разрешении.

**Comment by DarkRiDDeR** [comment]
Да, SVG неплохая технология, но я лично на практике не использовал ещё

**Comment by whitebyte** [comment]
Ничего сложного, вставляете вместо png в верстку и все. Все более-менее современные браузеры поддерживают. Логотип на dlang.org, например, именно в svg
