### ISSUE TITLE
Как запускать?

### ISSUE THREAD

**Issue by denizzzka** [DarkRiDDeR/inDCMS#7]
Как запускать CMS чтобы посмотреть как она работает?

**Comment by DarkRiDDeR** [comment]
Силь ещё смотреть то нечего, пока только регистрация и авторизация пользователей. Для запуска необходим сервер MySQL. Потом необходимо создать таблицы в бд, права доступа и администратора: файл development/install.sql Затем настроить доступ к бд в файле app.d:
db = new MySQL("host=localhost;port=3306;user=root;pwd=;db=dlang"); // settings
Ну и собираем проект с помощью dub

**Comment by denizzzka** [comment]
Короч, надо этот вопрос автоматизировать.
Тогда можно будет автоматически собирать и интеграционный тест делать.

Это в любом проекте надо как можно раньше организовывать - сразу скорость разработки вырастет.

**Comment by denizzzka** [comment]
Добавлю: надо сделать поддержку Travis-CI. Готов заняться, если по шагам объясните как оно сейчас собирается в том виде, в котором есть.

**Comment by DarkRiDDeR** [comment]
Неплохо. Я проект малость перепилю под PostgreSQL и хорошую поддуржку аддонов, а затем уже можно будет  сделать

**Comment by denizzzka** [comment]
А вот лучше наоборот! Сначала сделать сборку того что есть, а уже потом менять/переезжать/рефакторить.

**Comment by DarkRiDDeR** [comment]
Ну сейчас уже не собирётся ))

**Comment by denizzzka** [comment]
аа ) ну ок. в этом деле главное чтобы оно как можно быстрее начало собираться и выдавать хоть что-то (пустую страницу хоть)

**Comment by DarkRiDDeR** [comment]
Ну у меня авторизация и регистрация с MySQL уже работала

**Comment by denizzzka** [comment]
уже запускается?

**Comment by DarkRiDDeR** [comment]
Как бы да. Ещё немного автоматизирую и залью

**Comment by denizzzka** [comment]
Даже если она падает из-за https://github.com/DarkRiDDeR/inDCMS/issues/13 то всё равно имеет смысл сначала текущий тикет порешать.

**Comment by DarkRiDDeR** [comment]
Автоматическую сборку запилил
