### ISSUE TITLE
Как аддон добавляет свой html-код или код шаблона и контролы на сайт?

### ISSUE THREAD

**Issue by denizzzka** [DarkRiDDeR/inDCMS#9]
Есть документация?

Например, я хочу написать какой-нибудь отображатель последних n тем с форума

**Comment by DarkRiDDeR** [comment]
Добавление осуществляется с помощью шаблонизатора Temple.
https://github.com/dymk/temple
Документация там неплохая. inDCMS ещё слишком сыра для докуменатции, перепиливается

**Comment by denizzzka** [comment]
Я так понимаю, принцип будет таким:

движок доходит до мест, где требуется вставить некий вывод от какого-либо модуля и просит модуль этот текст ему выдать для вставки?

**Comment by DarkRiDDeR** [comment]
Впринципе да. Движок это по сути будет как клей для дополнений. Дополнения обрабатывают данные от пользователей, формируют данные для вывода в переменные ( с минимальным набором html-кода), а модуль Temple уже всё преобразует в html

**Comment by denizzzka** [comment]
аддоны возвращают html или код для шаблонизатора?

**Comment by denizzzka** [comment]
да, конечно код для шаблонизатора - чтобы на него уже потом наложить "скины" и прочее
